import numpy as np
import json
from collections import OrderedDict
import pandas as pd
import argparse

def all(file, snid, name):

    field, ra, dec, tobs, limmag, texp, prob, airmass, filt = np.loadtxt(file,unpack=True,dtype=str)
    ra,dec = ra.astype(float),dec.astype(float)

    tiles('2022B-922046_GW',[snid],ra,dec,filt,texp,[name],[snid],['object'],['GW-MMADS'],field)

def tiles(json_outpath,json_prefixs,pointRAs,pointDECs,filts,exps,propids,objects,exptypes,programs,fields):

    for json_prefix,pointRA,pointDEC,filt,exp,propid,tobject,exptype,program,field in zip(json_prefixs,pointRAs,pointDECs,filts,exps,objects,propids,exptypes,programs,fields):
        

        json_out = []
        cntr = 0
        lenobs = len(pointRAs)

        #print(lenobs)
        #print(filts)

        json_out.append('[')

        for i in range(lenobs):

                cntr += 1
                print(cntr)

                json_out.append('\t{') 
                json_out.append('\t\t"count": 1,')
                json_out.append('\t\t"filter": "%s",'% str(filts[i]))
                json_out.append('\t\t"exptime": %f,'% float(exps[i]))
                json_out.append('\t\t"RA": %f,' % round(float(pointRAs[i]), 5))
                json_out.append('\t\t"dec": %f,' % round(float(pointDECs[i]), 5))
                json_out.append('\t\t"object": "%s",'% (tobject + ' ' + str(field)))
                json_out.append('\t\t"program": "%s",'%program)
                json_out.append('\t\t"expType": "%s",'%exptype)
                json_out.append('\t\t"note": "None",')
                json_out.append('\t\t"comment": "%s",'%json_prefix)
                json_out.append('\t\t"wait": "False",')
                json_out.append('\t\t"proposer": "Andreoni Palmese",')
                json_out.append('\t\t"propid": "%s"'%propid)

                if cntr == lenobs:
                    json_out.append('\t}')
                else:            
                    json_out.append('\t},')

    
    json_out.append(']')
        
    np.savetxt(json_outpath+'/'+json_prefix+'.json', json_out, fmt='%s')

    print('wrote: '+json_outpath+'/'+json_prefix+'.json')
    

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Wrapper to convert gwemopt output to DECam pointings json file.")
    parser.add_argument("file", help="Pointings file generated by gwemopt.",type=str)
    parser.add_argument("snid", help="DECam Program ID.",type=str)
    parser.add_argument("name", help="Name of GW event (and name of the json file: name.json)",type=str)

    args = parser.parse_args()

    #snid = '2022B-922046'

    all(args.file, args.snid, args.name)


    #to run:
    #python gwemopt_to_json_DECam.py /Users/brendan/Documents/research/gwemopt/data/S230520ae/schedule_DECam.dat 2022B-922046 S230520ae






#